// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Voting$Type } from "./Voting";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Voting"]: Voting$Type;
    ["contracts/Voting.sol:Voting"]: Voting$Type;
  }
}
