// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Bank$Type } from "./Bank";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Bank"]: Bank$Type;
    ["contracts/Bank.sol:Bank"]: Bank$Type;
  }
}
